# Littering Resolution System Configuration

target_Y: 0.95
horizon_days: 90

# Initial system state
init_state: 
  Y: 0.80    # current outcome (80% compliance)
  N: 0.50    # norm strength
  A: 0.10    # attention level
  C: 0.30    # constraint strength
  B: 0.20    # burden level

# PID controller parameters
pid: 
  kp: 0.8          # proportional gain
  ki: 0.2          # integral gain
  kd: 0.1          # derivative gain
  deadband: 0.01   # deadband threshold
  max_step: 0.08   # maximum step size
  hysteresis: 0.02 # hysteresis threshold

# Fluctuation controller parameters (engineered gradients)
fluctuation:
  max_uF: 0.2           # maximum fluctuation control magnitude
  cooldown_days: 5      # minimum days between fluctuation pulses
  A_threshold: 0.6      # attention level that triggers consideration (lowered)
  stall_threshold: 0.015 # dY/dt threshold for detecting stalled progress

# Fast intervention arms (bandit choices)
fast_arms:
  - name: "injunctive"    # "most people don't litter"
    dose: 0.10
  - name: "descriptive"   # "see others not littering"
    dose: 0.10
  - name: "identity"      # "be someone who cares about community"
    dose: 0.10

# System parameter estimation inputs (improved for better resolution)
na_inputs: 
  sensing_features: 12       # number of sensing dimensions (increased)
  actuation_channels: 5      # number of control channels (increased)
  feedback_latency_days: 2   # feedback delay (decreased)

lambda_inputs: 
  cadence_days: 3           # intervention frequency (decreased)
  spatial_scale_km: 0.5     # spatial scale (decreased)

k1_inputs: 
  residual_std: 0.05        # model residual standard deviation (decreased)
  ops_variance: 0.03        # operational variance (decreased)
  habituation_rate: 0.03    # habituation/adaptation rate (decreased)

# Bandit reward threshold
reward_threshold: 0.92
